spring.application.name=fraud_javaServer
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=500MB

# Supabase PostgreSQL ?? ??
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.hrygwxiqjlxizstgirps
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ?? ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Supabase Storage ??
supabase.storage.url=https://hrygwxiqjlxizstgirps.supabase.co/storage/v1/object/fraud_image_collection/
supabase.api.key=${SUPABASE_API_KEY}
